### ISSUE TITLE
Can HAProxy be installed on FastDFS

### ISSUE THREAD

**Issue by UnicronHHH** [git001/haproxy#1]

**Comment by git001** [comment]
@UnicronHHH the question is to vague, that was also the reason why the question was closed on Stackoverflow.

* What is FastDFS?
* On which computer is FastDFS?
* What's your setup?

Because @UnicronHHH have deleted the original question I add it here.

**Can HAProxy be installed on FastDFS and provide HTTP services**

**Comment by UnicronHHH** [comment]
Thank you for your answer
Fastdfs is an open source distributed file system:https://github.com/happyfish100/fastdfs
I want to configure HAProxy on its Storage Server node
But the configuration failed
The error code is:
503 Service Unavailable
No Server is available to handle this request

**Comment by git001** [comment]
Because @UnicronHHH have deleted his answer I add it here
> Thank you for your answer
> Fastdfs is an open source distributed file system:https://github.com/happyfish100/fastdfs
> I want to configure HAProxy on its Storage Server node
> But the configuration failed
> The error code is:
> 503 Service Unavailable
> No Server is available to handle this request

Please can you share the following information's.

* `haproxy -vv`
* your haproxy config

**Comment by UnicronHHH** [comment]
> Can HAProxy be installed on FastDFS and provide HTTP services
